version: '3.8'

services:
  test-automation:
    build: .
    container_name: effective-mobile-tests
    working_dir: /app
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      - DISPLAY=:99